name: Dynamic Matrix
on: 
    workflow_dispatch:
        inputs:
            os:
                description: Operating Systems
                default: "windows-latest, ubuntu-latest"
                type: string
            node-version:
                description: Node Version
                default: "14,15,16"
                type: string
jobs:
    prepare-matrix:
        runs-on: ubuntu-latest
        steps:
            - run: echo "step-output=value" >> $GITHUB_OUTPUT
              id: step-1
            - run: echo "step-output=value 2" >> $GITHUB_OUTPUT
              id: step-2
            - run: |
                echo '${{ steps.step-1.outputs.step-output }}'
                echo '${{ steps.step-2.outputs.step-output }}'
    node_matrix:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
                node-version: [14,15,16]
        runs-on: ${{ matrix.os }}
        steps:
            - name: Check Node.js version before setup
              run: node -v
            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node-version }}
            - name: Check Node.js version after setup
              run: node -v
