name: Step Level Docker
on: workflow_dispatch
jobs:
    Message:
        runs-on: ubuntu-latest
        steps:
            - name: Send a Slack message
              uses: docker://technosophos/slack-notify
              env: 
                SLACK_WEBHOOK: ${{secrets.SLACK_WEBHOOK}}
                SLACK_TITLE: From Github Actions
                SLACK_MESSAGE: "Actor: ${{github.actor}}, Event: ${{ github.event_name }}"
                SLACK_COLOR: "#723fc4"